# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Record

# Model Form Field configuration
form: $/azaharizaman/octopusai/models/record/fields.yaml

# Model Class name
modelClass: AzahariZaman\OctopusAI\Models\Record

# Default redirect location
defaultRedirect: azaharizaman/octopusai/records

# Create page
create:
    title: backend::lang.form.create_title
    redirect: azaharizaman/octopusai/records/update/:id
    redirectClose: azaharizaman/octopusai/records

# Update page
update:
    title: backend::lang.form.update_title
    redirect: azaharizaman/octopusai/records
    redirectClose: azaharizaman/octopusai/records

# Preview page
preview:
    title: backend::lang.form.preview_title
